name: Deploy Docs

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Prepare Documentation Branch
        run: |
          echo "Culling all but the sacred docs folder..."
          # Remove everything except the .git directory and the docs folder
          find . -maxdepth=1 ! -name '.git' ! -name 'docs' -exec rm -rf {} +

      - name: Commit Docs to Documentation Branch
        run: |
          echo "Forging the documentation branch with our arcane docs folder..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B documentation
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Update docs folder from main branch"
          else
            echo "No changes to commit, our scheme remains unchanged."
          fi
          git push origin documentation

      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: documentation
          java-version: 23
          target-folder: docs/javadoc
          project: maven
