name: Deploy Docs

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Copy Main Content into Docs Folder
        run: |
          echo "Summoning the main branch into the docs folder..."
          mkdir -p docs
          shopt -s dotglob nullglob extglob
          cp -r !(docs) docs/

      - name: Commit Docs to Documentation Branch
        run: |
          echo "Forging the documentation branch with our pilfered main contents..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B documentation
          git add docs
          if ! git diff --cached --quiet; then
            git commit -m "Populate docs folder with main branch content"
          else
            echo "No changes to commit, nothing to alter in our grand design."
          fi
          git push origin documentation

      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: documentation
          java-version: 23
          target-folder: docs/javadoc
          project: maven
