# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created.
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        server-id: github  # Must match the distributionManagement/repository/id in your pom.xml
        settings-path: ${{ github.workspace }}  # Location for the settings.xml file

    - name: Update Maven version from release tag
      run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
      # Ensure the versions-maven-plugin is configured in your pom.xml if not already present.

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
